spring:
  application:
    name: nexus-platform-services
  profiles:
    active: local
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

server:
  port: 8080

logging:
  level:
    root: INFO
    com.nexus.platform: INFO

security:
  auth:
    enabled: true
    header-name: Authorization
    token-prefix: "Bearer "
    secret: ${JWT_SECRET:please-change-this-to-32chars-min-secret}
    issuer: nexus-platform-services
    expire-minutes: 120
    exclude-paths:
      - /api/auth/**
      - /error
      - /favicon.ico
